### ISSUE TITLE
Not working with react next js

### ISSUE THREAD

**Issue by trompx** [lukePeavey/SplitType#13]
Hello,

I was using an old version of splittype and recently migrated to next js.
I tried to use your new version `import SplitType from 'split-type'` but I get the following error:

```ts
Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
external%20%22split-type%22 (1:0) @ eval

> 1 | module.exports = require("split-type");
```
Any idea how to solve this?

**Comment by lukePeavey** [comment]
Did you install the latest version of split-type?

**Comment by lukePeavey** [comment]
@trompx sorry it took me a few days to respond

Just tested split-type with Next js, I am getting the same error.

**Comment by lukePeavey** [comment]
This should be fixed now. Try updating to [v0.2.5](https://github.com/lukePeavey/SplitType/releases/tag/v0.2.5). 


[CodeSandbox Example](https://codesandbox.io/s/splittype-next-example-ibo1n?file=/pages/index.js)

**Comment by lukePeavey** [comment]
I'm going to close this now since it's been resolved.

@trompx I'm not sure if you saw my previous comment, but this issue was fixed in version 0.2.5. Once you upgrade to the new version, SplitType should work fine with Next.js. If you are still having problems after upgrading to 0.2.5, let me know and I'll reopen this.

**Comment by trompx** [comment]
So sorry for answering this late, I've been caught by other projects. It works wonder now, no more errors, thanks !

**Comment by lukePeavey** [comment]
Great, glad to hear it!
