### ISSUE TITLE
Add type support for types property in options

### ISSUE THREAD

**Issue by StevenJPx2** [lukePeavey/SplitType#22]
Right now `types` in the `options?` parameter does not have any strict typing.

You can leverage template literals to give first-class typing for it:

```ts
type ElementSplitType = 'lines' | 'words' | 'chars'
type TypesAgg =
  | ElementSplitType
  | `${ElementSplitType} ${ElementSplitType}`
  | `${ElementSplitType} ${ElementSplitType} ${ElementSplitType}`
```

This will cover all bases and give excellent autocomplete suggestions.

**Comment by lukePeavey** [comment]
Good idea, want to submit a pr?

**Comment by lukePeavey** [comment]
@StevenJPx2 I just tested this out, it works great! I will definitely add this in the next update!

Just out of curiosity, do you know how you would create a similar type for an Array... an array that supports three values (lines, words, chars) in any combination, with autocomplete suggestions?

**Comment by lukePeavey** [comment]
I'll submit a PR shortly.
