### ISSUE TITLE
Break lines with strong div

### ISSUE THREAD

**Issue by dngraphisme** [lukePeavey/SplitType#42]
Hello @lukePeavey ,

Thank you already for this little library ! Well seen the takeover of splitText from Gsap. Less heavy in addition to size :)

However, I have a question that I still can't manage regarding the split lines and the <strong> or <span> or <em> tags.

Here is my HTML code :

```
<p>Installée dans un cabinet à Saint-Raphaël, auprès de mes amis Chiropracteur je vous
                        propose un accompagnement personnalisé à travers une approche holistique qui se traduit par la
                        considération de ses 3 points : <strong>Le bien-être psycho-émotionnel, physiologique (corps), et par le mode de vie.</strong></p>
```

My JS code :

```
window.$splitLines.each(function () {
                let $el = $(this),
                    $animText = $el.find($splitTextElements);

                $animText.each(function () {
                    let $lines = $(this);
                    SplitType.create($lines, {
                        types: "lines, words",
                        lineClass: "overflow-split-line",
                        wordClass: 'inline-block',
                    });
                    gsap.set(".overflow-split-line", {
                        overflow: "hidden"
                    });
                    gsap.set('.overflow-split-line > div, .overflow-split-line strong > div', {
                        yPercent: 105
                    });
                });
            });

```

Anyway I always have a newline with the <strong> tag, I also don't understand the part you mention in nested-elements

See my screenshot : https://ibb.co/tz4v0KX

Am I doing something wrong ?

Thanks for your return :) Regards Nicolas

**Comment by lukePeavey** [comment]
Nested elements are not fully compatible with splitting text into lines. 

As a workaround, you could wrap each word in a `<strong>` tag, instead of wrapping the entire sentence in a `<strong>` tag.   This will allow you to split the text into lines, and still maintain the original lines breaks. 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/8286271/177904761-8328a34c-58b5-4c0f-a2d7-79fbd02c4e96.png">

[Live Example on CodePen](https://codepen.io/lukePeavey/pen/zYBexbQ)

**Comment by dngraphisme** [comment]
Hello @lukePeavey,

Ok now I get it, I was thinking too. Gsap's SplitText has the same behavior. Too bad but it's already better than nothing.

Thank you very much for the quick response @lukePeavey  :)

**Comment by lukePeavey** [comment]
You're welcome.

**Comment by lukePeavey** [comment]
I'm going to close this, but feel free to post a comment if you have any other questions

**Comment by dimasadityamukhsinin** [comment]
hello, @lukePeavey 

It seems there's something wrong when I input this:

``<p id="split">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Nam in ante quis mi sollicitudin gravida eget congue tortor. Vivamus sit amet ipsum id sapien</strong> maximus hendrerit. Integer vehicula diam nec porta vulputate. Mauris sed metus varius, aliquam magna vitae, congue diam.</p>``

But the text inside the ``<strong>`` tag doesn't "split" as it should. Is there a solution?
