### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by jjcrl** [lukePeavey/SplitType#45]
Issues when importing SplitType within next.js. Errors with ''/node_modules/split-type/umd/index.js''

**Comment by lukePeavey** [comment]
I'll take a look at this...

Try importing it from ‘spit-type/dist’ and see if that works.

**Comment by jjcrl** [comment]
Thank you ! 
Still showing errors, `Server Error SyntaxError: Unexpected token 'export' `
 I've tried dynamic imports but had no luck with that either .

**Comment by lukePeavey** [comment]
@jjcrl Should be fixed in v0.3.2. 

Let me know if this worked for you.

**Comment by jjcrl** [comment]
updated to v0.3.2 and all working as expected. Thank you 🙏
