### ISSUE TITLE
Calling split() more than once results in 'undefined' text

### ISSUE THREAD

**Issue by danielkorte** [lukePeavey/SplitType#47]
Using the responsive text example code and resizing the window multiple times and you’ll see the issue:
https://codepen.io/danielkorte/pen/OJEVRoN

The reason for the issue is split() calls revert() which calls SplitType.revert() which deletes the 'html' cached data so the second run of split() will again call revert() but 'html' will be undefined at that point.

**Comment by lukePeavey** [comment]
Yeah I see what you mean...

**Comment by lukePeavey** [comment]
@danielkorte  Just released a patch for this. It should be fixed in 0.3.3.  Thanks for reporting this! 

Let me know if its working as expected in 0.3.3

**Comment by danielkorte** [comment]
Looks good to me — thanks!
