### ISSUE TITLE
How do we return type back to original html content after animation is finished??

### ISSUE THREAD

**Issue by shanewmurphy** [lukePeavey/SplitType#63]
How do we Implement the Reverting Split Text after animated is finished?

If use your gsap example of 

`const text = new SplitType('#target', { types: 'words, chars' })

// Animate characters into view with a stagger effect
gsap.from(text.chars, {
  opacity: 0,
  y: 20,
  duration: 0.5,
  stagger: { amount: 0.1 },
})`

How do we use SplitType.revert('#target') to return text to original html

**Comment by shanewmurphy** [comment]
I figured it out by 
`gsap.from(text.chars, {
opacity: 0,
y: 20,
duration: 0.5,
stagger: { amount: 0.1 },
 **onComplete: function () {
        SplitType.revert(".animate_text");
      },**
`

**Comment by lukePeavey** [comment]
@shanewmurphy going to close this since you found a solution.
